scholarec_web/scholarec_web/urls.py
## project wide urls
####################
from django.conf.urls import patterns, include, url
# from django.views.generic.simple import redirect_to
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse
from django.contrib import admin
admin.autodiscover()
import settings
from django.conf import settings

## urls from each app
#####################
import search.urls
import users.urls
from scholarec_web import views
'''
from haystack.forms import HighlightedModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView
from search.models import Article

article_sqs = SearchQuerySet().models(Article)
'''
# Patterns
urlpatterns = patterns('',
                       # urls specific to this app
                       
                       # social_auth (pip installed)
                       #url(r'', include('social_auth.urls')),

                       url(r'test', include(users.urls)),
                       # social auth git example app
                       #url('', include('social.apps.django_app.urls', namespace='social')),
                       
                       url(r'search/', include(search.urls)),
                       # Uncomment the admin/doc line below to enable admin documentation:
                       #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       # catch all, redirect to search home view
                       
                       #url(r'^.*/$', TemplateView.as_view(template_name="home.html")),
                       #(r'^$', 'search.views.index'),
                       #(r'^$', TemplateView.as_view(template_name="index.html",
                       #                content_type='text/plain')),

                       (r'^facebook/', include('django_facebook.urls')),
                       (r'^accounts/', include('django_facebook.auth_urls')), 
                       
                       (r'^profile/?$', views.profile),
                       (r'^$', views.home),
                       (r'^results/(?P<page>[\w.@+-]+)/?$', views.results,),
                       (r'^record/?$', views.record,),

                       (r'^fav/?$', views.fav,),
                       (r'^add/?$', views.add,),
                       (r'^remove/?$', views.remove,),

                       #(?P<username>[\w.@+-]+)/(?P<paper>[\w.@+-]+)/(?P<current>[\w.@+-]+)/(?P<q>[\w.@+-]+)/(?P<rate>[\w.@+-]+)/?$', views.fav,),
                       (r'^authors/$', views.authors),
                       (r'^citations/$', views.citations),
                       (r'^references/$', views.references),
                       (r'^raw/published/$', views.publish_stats),
                       (r'^raw/keywords/$', views.keyword_stats),
                       (r'^visualize/$', views.visualize),

                       #url(r'^social-auth/', 'scholarec_web.app.views.social_auth'),
                       url(r'^login/?$', 'scholarec_web.app.views.login'),
                       url(r'^signup-email/', 'scholarec_web.app.views.signup_email'),
                       url(r'^email-sent/', 'scholarec_web.app.views.validation_sent'),
                       url(r'^logout/$', 'scholarec_web.app.views.logout'),
                       url(r'^done/$', 'scholarec_web.app.views.done', name='done'),
                       url(r'^email/$', 'scholarec_web.app.views.require_email', name='require_email'),
                       url(r'', include('social.apps.django_app.urls', namespace='social')),
                       
)

if settings.MODE == 'userena':
    urlpatterns += patterns('',
                            (r'^accounts/', include('userena.urls')),
                        )
elif settings.MODE == 'django_registration':
    urlpatterns += patterns('',
                            (r'^accounts/', include(
                                'registration.backends.default.urls')),
                        )
    
    
if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT,
                            }),
    )

scholarec_web/social/apps/django_app/urls.py
"""URLs module"""
try:
    from django.conf.urls import patterns, url
except ImportError:
    # Django < 1.4
    from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('social.apps.django_app.views',
    # authentication / association
    url(r'^login/(?P<backend>[^/]+)/$', 'auth',
        name='begin'),
    url(r'^complete/(?P<backend>[^/]+)/$', 'complete',
        name='complete'),
    # disconnection
    url(r'^disconnect/(?P<backend>[^/]+)/$', 'disconnect',
        name='disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>[^/]+)/$',
        'disconnect', name='disconnect_individual'),
)

scholarec_web/users/urls.py
# app specific urls
from django.conf.urls import patterns, include, url
#from django.views.generic.simple import redirect_to
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse
from users import views

urlpatterns = patterns('',
                       (r'^$', views.test),
)

scholarec_web/scholarec_web/app/models.py
from django.db import models

# Create your models here.

scholarec_web/scholarec_web/models.py
from django.db import models
from django_facebook.models import FacebookProfileModel
from django.contrib.auth.models import UserManager
# Create your models here.

class MyCustomProfile(FacebookProfileModel):
    user = models.OneToOneField('auth.user')
    objects = UserManager()
    
from django.contrib.auth.models import User
from django.db.models.signals import post_save

#Make sure we create a MyCustomProfile when creating a User
def create_facebook_profile(sender, instance, created, **kwargs):
    if created:
        MyCustomProfile.objects.create(user=instance)
        
post_save.connect(create_facebook_profile, sender=User)  

scholarec_web/scholarec_web/app/views.py
from django.conf import settings
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from social.apps.django_app.utils import strategy

from social.backends.google import GooglePlusAuth


def logout(request):
    """Logs out user"""
    auth_logout(request)
    return render_to_response('login.html', {}, RequestContext(request))


def login(request):
    """Social Auth main view, displays login mechanism"""
    if request.user.is_authenticated():
        return redirect('done')
    return render_to_response('login.html', {
        'plus_id': getattr(settings, 'SOCIAL_AUTH_GOOGLE_PLUS_KEY', None)
    }, RequestContext(request))


@login_required
def done(request):
    """Login complete view, displays user data"""
    scope = ' '.join(GooglePlusAuth.DEFAULT_SCOPE)
    #print "whazzzuppp!! Guess what? I was just requested! \n",request,"\n"
    print "======================="
    print dir(strategy)
    print "======================="
    print dir(request)
    print "======================="
    return render_to_response('done.html', {
        'user': request.user,
        'plus_id': getattr(settings, 'SOCIAL_AUTH_GOOGLE_PLUS_KEY', None),
        'plus_scope': scope
    }, RequestContext(request))


def signup_email(request):
    return render_to_response('email_signup.html', {}, RequestContext(request))


def validation_sent(request):
    return render_to_response('validation_sent.html', {
        'email': request.session.get('email_validation_address')
    }, RequestContext(request))


def require_email(request):
    if request.method == 'POST':
        request.session['saved_email'] = request.POST.get('email')
        backend = request.session['partial_pipeline']['backend']
        return redirect('social:complete', backend=backend)
    return render_to_response('email.html', RequestContext(request))

scholarec_web/scholarec_web/views.py
# django specific
from django.core.context_processors import csrf
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
# app specific
import datetime
from dateutil.parser import parse
#from haystack.query import SearchQuerySet
from search import es_query
from users import control
#from users.models import History
from open_facebook import OpenFacebook
from django_facebook.api import get_persistent_graph
#import string
import json
from urllib import urlopen
import grequests

def home(request):    
    c = {}
    c.update(csrf(request))
    context = RequestContext(request)
    #print context
    return render_to_response('index.html', c, context)
    
def add(request):
    username = request.GET.get('username', None)
    p_id = request.GET.get('p_id', None)
    col_id = request.GET.get('col_id', None)
    title = request.GET.get('title', None)
    current = request.GET.get('current', None)
    q = request.GET.get('q', None)
    control.add_to_collection(username, col_id, p_id, title)
    return HttpResponseRedirect('/results/' + current + '?q=' + q)

def remove(request):
    username = request.GET.get('username', None)
    col_id = request.GET.get('col_id', None)
    current = request.GET.get('current', None)
    q = request.GET.get('q', None)
    control.remove_from_collection(username, col_id)
    return HttpResponseRedirect('/results/' + current + '?q=' + q)

def fav(request):
    username = request.GET.get('username', None)
    paper = request.GET.get('paper', None)
    current = request.GET.get('current', None)
    q = request.GET.get('q', None)
    rate = int(request.GET.get('rate', None))
    kw = request.GET.get('kw', None)
    print "FAVORITE req: username: %s paper_ID: %s Current_page: %s, Query: %s Rating: %s Keyword: %s " % \
        (username, paper, current, q, rate, kw)
    #table = string.maketrans("","")
    #kw = '%20'.join(kw.translate(table, string.punctuation).split())
    control.add_rating(username, paper, rate, q, kw)
    return HttpResponseRedirect('/results/' + current + '?q=' + q)

def profile(request):
    '''
    from django_facebook.api import get_facebook_graph, FacebookUserConverter, \
        get_persistent_graph, require_persistent_graph, get_user_attribute, \
        get_profile_model
    x = get_persistent_graph(request)
    #print require_persistent_graph(request)
    print dir(x.me)

    try:
        req = get_persistent_graph(request)
        graph = OpenFacebook(req.access_token)
        print "ME: ", graph.get('me')
    except:
        pass
    '''
    context = RequestContext(request)
    #x = context['user']

    '''
    #print graph.get('me')
    graph = request.user.get_offline_graph()
    print graph
    if graph:
        friends = graph.get('me/friends')
        print friends
    '''
    return render_to_response('profile.html', context)

def results(request, page):    
    query = request.GET.get('q', None)
    #print "page req: ", page
    #print SearchQuerySet().filter(content=query)
    #print "IN RESULTS: ", request.user #remember, user is an object
    if bool(query.split()):
        # add to search history
        history = control.add_to_history(query, str(request.user))
        if len(history) > 5:
            history = history[-5:]
        try:
            q_resp =  es_query.__run_query(query, search_from=int(page)-1, search_size=10)
            recos, favs = control.get_recommendations(str(request.user))
        except:
            return HttpResponse("Bad Request: Go back and check on your query parameters (mostly due to imbalanced \").")

        if bool(q_resp)==False:
            return HttpResponse('No results found! Go back')
            
        #print "\nQuery: %s" % (query)
        resp = []
        keywords = []
        _sources = q_resp['hits']['hits']
        for i in xrange(len(_sources)):
            temp = { 'title' : _sources[i]['_source']['title'],
                     #'authors' : '; '.join([j['name'] for j in _sources[i]['_source']['authors']]),
                     'authors' : [j['name'] for j in _sources[i]['_source']['authors']],
                     'summary' : _sources[i]['_source']['summary'],
                     'keyword' : _sources[i]['_source']['keyword'],
                     'published' : datetime.datetime.strptime(_sources[i]['_source']['published'], "%Y-%m-%dT%H:%M:%SZ"),
                     'ID' : _sources[i]['_source']['ID'],
                     'id' : _sources[i]['_id'],
                     'links' : [ {'href':j['href'],'type':j['type']} for j in _sources[i]['_source']['links']]
                     #'links' : '; '.join([j['href'] for j in _sources[i]['_source']['links']])
                 }
            
            keywords.append(_sources[i]['_source']['keyword'])
            resp.append(temp)
            
        return render_to_response('results.html', 
                                  { 'items' : resp, 
                                    'history' : history, 
                                    'collection' : control.get_collection(str(request.user)),
                                    'username' : str(request.user),
                                    'recommendations' : recos,
                                    'favorites' : favs,
                                    'total' : q_resp['hits']['total'],
                                    'took' : float(q_resp['took'])/1000, 
                                    'keywords' : list(set(keywords)),
                                    'current' : page,
                                    'q' : query })
    else:
        #return HttpResponse("No Query Sent!")
        return HttpResponseRedirect('/search/')

def record(request):
    doc_id = request.GET.get('doc', None)
    query = request.GET.get('q', None)
    try:
        response = urlopen('http://localhost:9200/arxiv/docs/'+ \
                           doc_id + '/_source')
    except:
        return HttpResponse('404: Not Found! Go back')
    result = json.loads(response.read())
    temp = []
    for a in result['authors']:
        temp.append(a['name'])
    result['authors'] = temp
    result['published'] = datetime.datetime.strptime(
        result['published'], "%Y-%m-%dT%H:%M:%SZ")
    return render_to_response('record.html', \
                              { 'item' : result,
                                'q' : query })

def authors(request):    
    return render_to_response('authors.html', {})

def citations(request):    
    return render_to_response('citations.html', {})

def references(request):    
    return render_to_response('references.html', {})

def publish_stats(request):    
    URL = "http://localhost:9200/arxiv/docs/_search"
    temp = """{
    "size": 0,
    "aggs": {
    "publish_stats": {
    "date_histogram": {
    "field": "published",
    "interval": "year"
    }}}}"""
    resp = grequests.map([grequests.post(URL, data=temp)])
    data = json.loads(resp[0].content)
    temp = data['aggregations']['publish_stats']['buckets']
    l = [['key_as_string', 'doc_count']]
    for i in temp:
        l.append([i[l[0][0]][:4],
                  #parse(i[l[0][0]]).strftime("%A,%e %B %G"),
                  i[l[0][1]]])
    return HttpResponse(json.dumps(l), content_type="application/json")

def keyword_stats(request):    
    URL = "http://localhost:9200/arxiv/docs/_search"
    temp = """{
    "size":0,
    "aggs":{
    "keyword_stats":{
    "terms":{
    "field":"keyword",
    "size": 200
    }}}}"""
    # "shard_size": 100 
    # Refer docs: ES search aggregations bucket terms aggregation
    resp = grequests.map([grequests.post(URL, data=temp)])
    data = json.loads(resp[0].content)
    temp = data['aggregations']['keyword_stats']['buckets']
    l = [['key', 'doc_count']]
    for i in temp:
        l.append([i[l[0][0]],
                  #parse(i[l[0][0]]).strftime("%A,%e %B %G"),
                  i[l[0][1]]])
    return HttpResponse(json.dumps(l), content_type="application/json")

def visualize(request):
    return render_to_response('viz.html')

scholarec_web/scholarec_web/templates/authors.html
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      html { height: 100% }
      body { 
        height: 100%; margin: 0; padding: 0; font-size: 12px;
        background-color: #EEE;
      }
      .node {
        stroke: #fff;
        stroke-width: 1.5px;
      }

      .link {
        stroke: #999;
        stroke-opacity: .6;
      }
    </style>
    <script src="/static/js/jquery/jquery-1.8.3.min.js"></script>
    <script src="/static/js/d3/d3.v3.min.js"></script>
    <script type="text/javascript">

    if (!String.prototype.format) {
      String.prototype.format = function() {
        var args = arguments;
        return this.replace(/{(\d+)}/g, function(match, number) { 
          return typeof args[number] != 'undefined'
            ? args[number]
            : match
          ;
        });
      };
    }

    var json = [];
    $(document).ready(function(){

    // load database as JSON
    $.getJSON("/static/json/db.json", function(jsondb) {
    json = jsondb;

      // some preprocessing here 
      var N = json.length;
      //N=100;
    
      var adeg = {};
      for(var i=0;i<N;i++) {
        var j = json[i];
        for(var k=0;k<j.a.length;k++){
          jak = j.a[k];
          if(jak in adeg) {
            adeg[jak]+=1;
          } else {
            adeg[jak]=1;
          }
        }
      }
      
      var coauthors = {};
      var links = [];
      for(var i=0;i<N;i++) {
        var j = json[i];  

        // first figure out if we count this paper. It must be at least decent
        var rank = 0
        if (parseInt(j.y) !== 0) { rank = parseInt(j.cn) / (2013 - parseInt(j.y)); }
        rank = Math.round(rank);
        if(rank<0 || j.y<700) continue;

        // maintain affinities for authors
        for(var k=0;k<j.a.length;k++){
          var a = j.a[k];
          if(!(a in coauthors)) coauthors[a] = {};

          for(var k2=0;k2<j.a.length;k2++){
            if(k===k2) continue;
            var a2= j.a[k2];
            if(!(a2 in coauthors[a])) {
              coauthors[a][a2] = 1; // add them
            } else {
              coauthors[a][a2] = coauthors[a][a2] + 1; // increase affinity
            }
          }
        }
      }

      // construct the graph
      var nodes = [];
      var authors = [];
      for(var a in coauthors) {
        var ca = coauthors[a];
        for(var a2 in ca) {
          var w = ca[a2];
          if(w > 1) {
            // add this to graph
            var ix1 = $.inArray(a, authors);
            var ix2 = $.inArray(a2, authors);
            if(ix1===-1) {authors.push(a); ix1=authors.length-1; nodes.push({name: a, group: 1, d: adeg[a]})}
            if(ix2===-1) {authors.push(a2); ix2=authors.length-1; nodes.push({name: a2, group: 1, d: adeg[a2]})}
            if(ix1<ix2) { // make sure we dont go both directions. that's silly
              links.push({source: ix1, target: ix2, value: w});
            }
          }
        }
      }

      // these, and the charge and linkDistance below have to be played with
      var width = 1200; 
      var height = 700;

      var color = d3.scale.category20();
      var force = d3.layout.force()
          .charge(-120)
          .linkDistance(70)
          .size([width, height]);

      var svg = d3.select("body").append("svg")
          .attr("width", width)
          .attr("height", height);

        force
            .nodes(nodes)
            .links(links)
            .start();

        var link = svg.selectAll(".link")
            .data(links)
            .enter().append("line")
            .attr("class", "link")
            .style("stroke-width", function(d) { return Math.sqrt(d.value); });

        /*
        // instead of text can show little circles with this code
        var node = svg.selectAll(".node")
            .data(nodes)
            .enter().append("circle")
            .attr("class", "node")
            .attr("r", 5)
            .style("fill", function(d) { return color(d.group); })
            .call(force.drag);

        node.append("title")
            .text(function(d) { return d.name; })
            .style("fill", "#555")
            .call(force.drag);
        */
        
        var node = svg.selectAll(".node")
            .data(nodes)
            .enter().append("text")
            .text(function(d){return d.name;})
            .style("font-size", function(d) { return (Math.round(d.d)+12) + "px"; })
            .call(force.drag);
        

        force.on("tick", function() {
          link.attr("x1", function(d) { return d.source.x; })
              .attr("y1", function(d) { return d.source.y; })
              .attr("x2", function(d) { return d.target.x; })
              .attr("y2", function(d) { return d.target.y; });

          node.attr("dx", function(d) { return d.x; })
              .attr("dy", function(d) { return d.y; });
        });
			});

    });

    </script>
  </head>
  <body>
  </body>
</html>

scholarec_web/scholarec_web/templates/base_viz.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>ScholaRec stats</title>
    <link rel="stylesheet" href="/static/viz/styles.css">
    <link rel="stylesheet" href="/static/viz/pygment_trac.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    {% block header%}
    {% endblock %}
    <script src="/static/viz/scale.fix.js"></script>
  </head>

  <body>
    <div class="wrapper">
      <center>
	<a href="/">
	  <img class="muted" src="/static/img/scholarec_icon.png"></a><strong style="color: #B11C46;">Analytics</strong>
      </center>
    </div>
    <hr />    
    {% block content %}{% endblock %}    
  </body>
  {% block footer %}{% endblock %}
</html>

scholarec_web/scholarec_web/templates/citations.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Popular physics in history</title>

<!-- CSS Files -->
<link type="text/css" href="/static/js/jit/css/base.css" rel="stylesheet" />
<link type="text/css" href="/static/js/jit/css/ForceDirected.css" rel="stylesheet" />

<!-- JIT Library File -->
<script language="javascript" type="text/javascript" src="/static/js/jit/jit.js"></script>
<script type="text/javascript" src="/static/json/authors.json"></script>

<!-- Example File -->
<script language="javascript" type="text/javascript" src="/static/js/jit/example1.js"></script>
</head>

<body onload="init();">
<div id="container">

<div id="center-container">
    <div id="infovis"></div>    
</div>

<div id="right-container">

<div id="inner-details"></div>

</div>

<div id="log"></div>
</div>
</body>
</html>

scholarec_web/scholarec_web/templates/email.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <label for="email">Email address:</label>
  <input id="email" type="email" name="email" value="" />
  <button>Save</button>
</form>
{% endblock %}

scholarec_web/scholarec_web/templates/login.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}

<div class="col-lg-6">
  <ol>
    <li>
      <a href="/facebook/connect">
	<button type="button" class="btn btn-info">FaceBook (OAuth2)
	</button>
      </a>
    </li>
    <li>
      <a href="{% url 'social:begin' 'twitter' %}">
	<button type="button" class="btn btn-default">Twitter (OAuth1)
	</button>
      </a>
    </li>
    <li>
      <a href="{% url 'social:begin' 'google' %}">
	<button type="button" class="btn btn-primary">Google (OpenId)
	</button>
      </a>
    </li>
    <li>
      <a href="{% url 'social:begin' 'github' %}">
	<button type="button" class="btn btn-success">Github (OAuth2)
	</button>
      </a>
    </li>  
    <li>
      <a href="{% url 'social:begin' 'linkedin' %}">
	<button type="button" class="btn btn-info">LinkedIn OAuth1
	</button> 
      </a>
    </li>
    <li>
      <a href="{% url 'social:begin' 'username' %}">
	<button type="button" class="btn btn-danger">Username Auth
	</button>
      </a>
    </li>
    <li>
      <form method="post" action="{% url 'social:complete' 'persona' %}">{% csrf_token %}
	<input type="hidden" name="assertion" value="" />
	<a rel="nofollow" id="persona" href="#">
	  <button type="button" class="btn btn-default">Persona (Mozilla Browser ID)
	  </button>
	</a>
      </form>
    </li>		
    <li>
      <a href="{% url 'social:begin' 'email' %}">
	<button type="button" class="btn btn-warning">Email Auth
	</button>
      </a>
    </li>
  </ol>
</div>

<div class="col-lg-6" >
  <ul>
    <li><a href="{% url 'social:begin' 'facebook' %}">
	<button type="button" class="btn btn-primary btn-sm">Facebook (OAuth2)
    </button></a></li>
    <li><a href="{% url 'social:begin' 'facebook-app' %}">
	<button type="button" class="btn btn-primary btn-sm">Facebook (App)
	</button>
    </a> </li>
    <li><a href="{% url 'social:begin' 'fedora' %}">
	<button type="button" class="btn btn-primary btn-sm">Fedora (OpenId)
    </button></a> </li>
    <li><a href="{% url 'social:begin' 'flickr' %}">
	<button type="button" class="btn btn-primary btn-sm">Flickr (OAuth1)
    </button></a> </li>
    <li><a href="{% url 'social:begin' 'google-oauth' %}">
	<button type="button" class="btn btn-primary btn-sm">Google OAuth1
    </button></a> </li>
    <li><a href="{% url 'social:begin' 'google-oauth2' %}">
	<button type="button" class="btn btn-primary btn-sm">Google OAuth2
    </button></a></li>
    <li><a href="{% url 'social:begin' 'linkedin-oauth2' %}">
	<button type="button" class="btn btn-primary btn-sm">LinkedIn OAuth2
    </button></a> </li>
    <li><a href="{% url 'social:begin' 'reddit' %}">
	<button type="button" class="btn btn-primary btn-sm">Reddit OAuth2
    </button></a> </li>
    <li><a href="{% url 'social:begin' 'soundcloud' %}">
	<button type="button" class="btn btn-primary btn-sm">Soundcloud OAuth2
    </button></a> </li>
    <li><a href="{% url 'social:begin' 'stackoverflow' %}">
	<button type="button" class="btn btn-primary btn-sm">Stackoverflow OAuth2
    </button></a> </li>
    <li><a href="{% url 'social:begin' 'tumblr' %}">
	<button type="button" class="btn btn-primary btn-sm">Tumblr OAuth1
    </button></a> </li>
    <li><a href="{% url 'social:begin' 'yahoo' %}">
	<button type="button" class="btn btn-primary btn-sm">Yahoo OpenId
    </button></a> </li>
    <li><a href="{% url 'social:begin' 'yahoo-oauth' %}">
	<button type="button" class="btn btn-primary btn-sm">Yahoo OAuth1
    </button></a> </li>
    <li>
      <form action="{% url 'social:begin' 'openid' %}" method="post">{% csrf_token %}
	<div>
	  <label for="openid_identifier">OpenId provider</label>
	  <input id="openid_identifier" type="text" value="" name="openid_identifier" />
	  <input type="submit" value="Login" />
	</div>
      </form>
    </li>
    <li>
      <form action="{% url 'social:begin' 'livejournal' %}" method="post">{% csrf_token %}
	<div>
	  <label for="openid_lj_identifier">LiveJournal ID</label>
	  <input id="openid_lj_identifier" type="text" value="" name="openid_lj_user" />
	  <input type="submit" value="Login" />
	</div>
      </form>
    </li>
  </ul>    
  {% if plus_id %}
  
  <form id="google-plus" method="post" action="{% url 'social:complete' 'google-plus' %}">{% csrf_token %}
    <input id="at" type="hidden" name="access_token" value="" />
    <input id="code" type="hidden" name="code" value="" />
    <div id="signinButton">
      <span class="g-signin" data-scope="{{ plus_scope }}"
	    data-clientid="{{ plus_id }}"
	    data-redirecturi="postmessage"
	    data-accesstype="offline"
	    data-cookiepolicy="single_host_origin"
	    data-callback="signInCallback">
      </span>
    </div>
  </form>
  {% endif %}
  {% endblock %}
</div>
{% block head_scripts %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
<script src="https://login.persona.org/include.js" type="text/javascript"></script>

<!-- Mozilla Persona -->
<script type="text/javascript">
  $(function () {
  $('#persona').on('click', function (e) {
  e.preventDefault();
  var self = $(this);
  
  navigator.id.get(function (assertion) {
  if (assertion) {
  self.parent('form')
  .find('input[type=hidden]')
  .attr('value', assertion)
  .end()
  .submit();
  } else {
  alert('Some error occurred');
  }
  });
  });
  });
</script>

<!-- Google+ Sign In -->
<script type="text/javascript">
  (function () {
  var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true; po.src = 'https://plus.google.com/js/client:plusone.js?onload=start';
  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(po, s);
  })();
</script>

<script type="text/javascript">
  var signInCallback = function (result) {
  if (result['error']) {
  alert('An error happened:', result['error']);
  } else {
  $('#code').attr('value', result['code']);
  $('#at').attr('value', result['access_token']);
  $('#google-plus').submit();
  }
  };
</script>
{% endblock %}

scholarec_web/scholarec_web/templates/test.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>ScholaRec| Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all"/>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>